language: ruby
sudo: false
rvm:
  - 2.1.0
  - 2.2.2
script: bundle exec rake
notifications:
  webhooks:
    urls:
      - "https://pitaleerb.slack.com/services/hooks/travis?token=wNtbVP9B3j1npZkLzK4bpq8Q"
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
